name: mailhog-mailserver
services:
    mailhog:
        ports:
            - 1025:1025 # Mailhog listens on 1025 for SMTP
            - 8025:8025 # Mailhog's web UI listens on 8025
        container_name: mailhog
        image: docker.io/mailhog/mailhog
        