FROM debian:trixie

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    make \
    git \
    just \
    psutils \
    tmux \
    neovim \
    vim \
    joe \
    nano \
    pip \
    man \
    curl \
    wget

ENTRYPOINT ["bash"]
