
name: traefik
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_default
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_default"
      - "--entryPoints.web.address=:8090"
      - "--entryPoints.websecure.address=:8443"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    ports:
      - "8090:8090"
      - "8443:8443"
      - "8088:8080" # Traefik dashboard
    volumes:
      - "/var/run/podman/podman.sock:/var/run/docker.sock" #Needed for rootfull podman


networks:
  traefik_default :
    name: traefik_default 
