name: plantuml
services:
    plantumlserver:
        container_name: "planuml-server"
        ports:
            - 9003:8080
        image: plantuml/plantuml-server:jetty
        labels:
            #- "traefik.enable=true"
            - "traefik.http.routers.plantumlserver.rule=Host('plantuml.localhost')"
            #- "traefik.http.routers.plantumlserver.entrypoints=web"
            #- "traefik.http.routers.frontend.service=plantumlserver"
        networks:
            - traefik_default
networks:
  traefik_default :
    name: traefik_default
    external: true